import * as DTOs from '@/entities/DTOs'

export const Rights = [
  { key: 'GD', title: 'Генеральный директор' },
  { key: 'DP', title: 'Директор производства' },
  { key: 'ROK', title: 'Руководитель отдела координации' },
  { key: 'RAO', title: 'Рук. Админст. отдела' },
  { key: 'ASP', title: 'Ассистент производства' },
  { key: 'ASS', title: 'Ассистент продаж' },
  { key: 'SHR', title: 'Расширенные права HR руководителя' },
  { key: 'RHR', title: 'HR руководитель' },
  { key: 'MHR', title: 'HR менеджер' },
  { key: 'GIP', title: 'Ведущий инженер' },
  { key: 'GI', title: 'Главный инженер' },
  { key: 'NU', title: 'Начальник участка' },
  { key: 'PR', title: 'Прораб' },
  { key: 'NS', title: 'Начальник склада' },
  { key: 'MPS', title: 'Менеджер продаж склада' },
  { key: 'MOS', title: 'Менеджер отгрузок склада' },
  { key: 'VD', title: 'Водитель' },
  { key: 'MS', title: 'Мастер (без аккаунта)' },
  { key: 'PD', title: 'Подряд (без аккаунта)' },
  { key: 'ROS', title: 'РОП сметчиков' },
  { key: 'SM', title: 'Сметчик' },
  { key: 'RSN', title: 'Руководитель снабжения' },
  { key: 'MSN', title: 'Менеджер снабжения' },
  { key: 'RCH', title: 'Руководитель черновых' },
  { key: 'MCH', title: 'Менеджер черновых' },
  { key: 'RPM', title: 'Руководитель чист. мат.' },
  { key: 'MPM', title: 'Менеджер чист. мат.' },
  { key: 'DDZ', title: 'Директор дизайнеров' },
  { key: 'RDZ', title: 'РОП дизайнеров' },
  { key: 'DZ', title: 'Дизайнер' },
  { key: 'MDZ', title: 'Младший дизайнер' },
  { key: 'RCC', title: 'Руководитель кол-центра' },
  { key: 'ROC', title: 'РОП кол-центра' },
  { key: 'CC', title: 'Менеджер кол-центра' },
  { key: 'LDV', title: 'Руководитель дверей' },
  { key: 'RDV', title: 'РОП дверей' },
  { key: 'MDV', title: 'Менеджер дверей' },
  { key: 'LCM', title: 'Руководитель комплектации' },
  { key: 'RCM', title: 'Комплектовщик' },
  { key: 'SRDZ', title: 'Старший РОП дизайнеров' },
  { key: 'teamlead_complect', title: 'Распределение комплектации' },
  { key: 'DEV', title: 'Разработчик' },
  { key: 'tech_nadzor', title: 'Тех. Надзор' }
] as DTOs.RightDTO.RightDTO[]
